import { useEffect, useState } from "react";

const windows = ["C1", "C2", "C3"];

export default function CaaoExplainer() {
  const [reduced, setReduced] = useState(false);
  const [cursor, setCursor] = useState(0);
  useEffect(() => {
    const media = window.matchMedia("(prefers-reduced-motion: reduce)");
    const sync = () => setReduced(media.matches);
    sync();
    media.addEventListener?.("change", sync);
    const timer = window.setInterval(() => setCursor((value) => (value + 1) % windows.length), 3000);
    return () => { media.removeEventListener?.("change", sync); window.clearInterval(timer); };
  }, []);
  const active = windows[cursor];
  return <div className={`caao-explainer caao-paper ${reduced ? "is-reduced" : ""}`} role="img" aria-label="Paper-faithful CAAO animation showing model components mapped to virtual memory: CPU pinned backing store, GPU physical page frames, and overlapping prefetch, compute, offload, and update streams.">
    <div className="caao-header"><span>PIPELINED CAAO / VIRTUAL MEMORY MANAGEMENT</span><b>IMPLEMENTATION TRACE <i>●</i></b></div>
    <svg viewBox="0 0 960 520" preserveAspectRatio="xMidYMid meet" aria-hidden="true">
      <defs><marker id="paperArrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0 L10 5 L0 10 z" fill="#8a8f98" /></marker><linearGradient id="paperDma" x1="0" x2="1"><stop stopColor="#5b7fdb" /><stop offset=".5" stopColor="#8fd6e8" /><stop offset="1" stopColor="#c6e86b" /></linearGradient><radialGradient id="paperCompute"><stop stopColor="#c6e86b" stopOpacity=".32" /><stop offset="1" stopColor="#c6e86b" stopOpacity="0" /></radialGradient></defs>
      <text x="42" y="30" className="paper-muted">MODEL COMPONENTS → VIRTUAL MEMORY PAGES → CUDA STREAMS</text>
      <g className="paper-decomp"><text x="42" y="64" className="paper-cyan">COMPONENT MANAGEMENT MODULE</text><g className="paper-nodes">{[[58,88],[88,112],[64,136],[112,92],[132,126],[158,104]].map(([x,y], i) => <circle key={i} cx={x} cy={y} r="4" />)}{[[58,88,88,112],[88,112,64,136],[88,112,112,92],[112,92,132,126],[132,126,158,104]].map(([x1,y1,x2,y2], i) => <path key={i} d={`M${x1} ${y1} L${x2} ${y2}`} />)}</g><path className="paper-arrow" d="M178 112 H230" markerEnd="url(#paperArrow)" /><g className="paper-components">{["C1", "C2", "C3", "C4"].map((label, i) => <g key={label} transform={`translate(${242 + i * 76} 92)`}><rect width="58" height="34" rx="3" /><text x="29" y="22" textAnchor="middle">{label}</text></g>)}</g><text x="242" y="143" className="paper-muted">split model into executable components</text></g>
      <g className="paper-memory"><rect className="paper-cpu" x="42" y="174" width="250" height="134" rx="4" /><text x="60" y="199" className="paper-blue">CPU RAM / SWAP BACKING STORE</text><text x="60" y="220" className="paper-muted">PINNED HOST MEMORY</text>{["C1", "C2", "C3", "C4"].map((label, i) => <g key={label}><rect className="paper-page" x={60 + (i % 2) * 112} y={238 + Math.floor(i / 2) * 34} width="90" height="23" rx="2" /><text x={105 + (i % 2) * 112} y={254 + Math.floor(i / 2) * 34} textAnchor="middle" className="paper-chip-blue">{label} / PAGE</text></g>)}</g>
      <g className="paper-memory"><rect className="paper-gpu" x="668" y="174" width="250" height="134" rx="4" /><text x="686" y="199" className="paper-green">GPU VRAM / PHYSICAL PAGE FRAME</text><text x="686" y="220" className="paper-muted">ACTIVE WORKING SET / 3 PAGES</text><circle className="paper-glow" cx="794" cy="270" r="48" /><rect className="paper-active-page" x="690" y="244" width="66" height="30" rx="2" /><rect className="paper-active-page is-active" x="766" y="244" width="66" height="30" rx="2" /><rect className="paper-active-page" x="842" y="244" width="66" height="30" rx="2" /><text x="723" y="263" textAnchor="middle" className="paper-chip-green">{active}</text><text x="799" y="263" textAnchor="middle" className="paper-chip-green">{active === "C1" ? "C2" : active === "C2" ? "C3" : "C4"}</text><text x="875" y="263" textAnchor="middle" className="paper-chip-green">NEXT</text></g>
      <path className="paper-dma-line" d="M292 241 H668" /><text x="480" y="225" textAnchor="middle" className="paper-cyan">PCIe / DMA — NO BOUNCE BUFFER</text><g className="paper-transfer"><g className="paper-prefetch-group"><rect className="paper-prefetch" x="408" y="231" width="58" height="22" rx="2" /><text x="437" y="246" textAnchor="middle" className="paper-chip-cyan">C[i+1]</text></g><g className="paper-offload-group"><rect className="paper-offload" x="500" y="266" width="58" height="22" rx="2" /><text x="529" y="281" textAnchor="middle" className="paper-chip-blue">C[i−1]</text></g></g>
      <g className="paper-pipeline"><text x="42" y="346" className="paper-cyan">FOUR-STAGE CUDA STREAM OVERLAP</text><line x1="42" y1="364" x2="918" y2="364" className="paper-rule" /><text x="58" y="390" className="paper-stage-cyan">PIPE 1 / PREFETCH</text><text x="284" y="390" className="paper-stage-green">PIPE 2 / COMPUTE</text><text x="510" y="390" className="paper-stage-blue">PIPE 3 / OFFLOAD</text><text x="736" y="390" className="paper-stage-muted">PIPE 4 / UPDATE</text><rect className="paper-lane lane-prefetch" x="58" y="405" width="185" height="12" rx="2" /><rect className="paper-lane lane-compute" x="284" y="405" width="185" height="12" rx="2" /><rect className="paper-lane lane-offload" x="510" y="405" width="185" height="12" rx="2" /><rect className="paper-lane lane-update" x="736" y="405" width="130" height="12" rx="2" /><text x="58" y="440" className="paper-muted">C[i+1] page-in</text><text x="284" y="440" className="paper-muted">C[i] forward / backward</text><text x="510" y="440" className="paper-muted">C[i−1] deterministic page-out</text><text x="736" y="440" className="paper-muted">CPU optimizer thread</text></g>
      <g className="paper-condition"><rect x="42" y="463" width="876" height="34" rx="3" /><text x="60" y="485" className="paper-cyan">OVERLAP CONDITION</text><text x="236" y="485" className="paper-equation">T_compute ≥ max(T_page in, T_page out)</text><text x="730" y="485" className="paper-muted">ACTIVE WINDOW: {active} → next</text></g>
    </svg>
  </div>;
}
